package entities;
// Generated 24/04/2019 05:26:35 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private String deptno;
     private String deptname;
     private String mgrno;
     private String admrdept;
     private String location;
     private Set projects = new HashSet(0);
     private Set employees = new HashSet(0);

    public Department() {
    }

	
    public Department(String deptno, String deptname, String admrdept) {
        this.deptno = deptno;
        this.deptname = deptname;
        this.admrdept = admrdept;
    }
    public Department(String deptno, String deptname, String mgrno, String admrdept, String location) {
       this.deptno = deptno;
       this.deptname = deptname;
       this.mgrno = mgrno;
       this.admrdept = admrdept;
       this.location = location;
    }
   
    public String getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }
    public String getDeptname() {
        return this.deptname;
    }
    
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }
    public String getMgrno() {
        return this.mgrno;
    }
    
    public void setMgrno(String mgrno) {
        this.mgrno = mgrno;
    }
    public String getAdmrdept() {
        return this.admrdept;
    }
    
    public void setAdmrdept(String admrdept) {
        this.admrdept = admrdept;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }


}


