package entities;
// Generated 24/04/2019 05:26:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EmpAct generated by hbm2java
 */
public class EmpAct  implements java.io.Serializable {


     private int id;
     private Employee empno;
     private Project projno;
     private short actno;
     private BigDecimal emptime;
     private Date emstdate;
     private Date emendate;

    public EmpAct() {
    }

	
    public EmpAct(int id, Employee empno, Project projno, short actno) {
        this.id = id;
        this.empno = empno;
        this.projno = projno;
        this.actno = actno;
    }
    public EmpAct(int id, Employee empno, Project projno, short actno, BigDecimal emptime, Date emstdate, Date emendate) {
       this.id = id;
       this.empno = empno;
       this.projno = projno;
       this.actno = actno;
       this.emptime = emptime;
       this.emstdate = emstdate;
       this.emendate = emendate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Employee getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(Employee empno) {
        this.empno = empno;
    }
    public Project getProjno() {
        return this.projno;
    }
    
    public void setProjno(Project projno) {
        this.projno = projno;
    }
    public short getActno() {
        return this.actno;
    }
    
    public void setActno(short actno) {
        this.actno = actno;
    }
    public BigDecimal getEmptime() {
        return this.emptime;
    }
    
    public void setEmptime(BigDecimal emptime) {
        this.emptime = emptime;
    }
    public Date getEmstdate() {
        return this.emstdate;
    }
    
    public void setEmstdate(Date emstdate) {
        this.emstdate = emstdate;
    }
    public Date getEmendate() {
        return this.emendate;
    }
    
    public void setEmendate(Date emendate) {
        this.emendate = emendate;
    }




}


