package entities;
// Generated 24/04/2019 05:26:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private String empno;
     private String firstnme;
     private char midinit;
     private String lastname;
     private Department workdept;
     private String phoneno;
     private Date hiredate;
     private String job;
     private short edlevel;
     private Character sex;
     private Date birthdate;
     private BigDecimal salary;
     private BigDecimal bonus;
     private BigDecimal comm;

    public Employee() {
    }

	
    public Employee(String empno, String firstnme, char midinit, String lastname, short edlevel) {
        this.empno = empno;
        this.firstnme = firstnme;
        this.midinit = midinit;
        this.lastname = lastname;
        this.edlevel = edlevel;
    }
    public Employee(String empno, String firstnme, char midinit, String lastname, Department workdept, String phoneno, Date hiredate, String job, short edlevel, Character sex, Date birthdate, BigDecimal salary, BigDecimal bonus, BigDecimal comm) {
       this.empno = empno;
       this.firstnme = firstnme;
       this.midinit = midinit;
       this.lastname = lastname;
       this.workdept = workdept;
       this.phoneno = phoneno;
       this.hiredate = hiredate;
       this.job = job;
       this.edlevel = edlevel;
       this.sex = sex;
       this.birthdate = birthdate;
       this.salary = salary;
       this.bonus = bonus;
       this.comm = comm;
    }
   
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }
    public String getFirstnme() {
        return this.firstnme;
    }
    
    public void setFirstnme(String firstnme) {
        this.firstnme = firstnme;
    }
    public char getMidinit() {
        return this.midinit;
    }
    
    public void setMidinit(char midinit) {
        this.midinit = midinit;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Department getWorkdept() {
        return this.workdept;
    }
    
    public void setWorkdept(Department workdept) {
        this.workdept = workdept;
    }
    public String getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
    public Date getHiredate() {
        return this.hiredate;
    }
    
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public short getEdlevel() {
        return this.edlevel;
    }
    
    public void setEdlevel(short edlevel) {
        this.edlevel = edlevel;
    }
    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }
    public BigDecimal getBonus() {
        return this.bonus;
    }
    
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }
    public BigDecimal getComm() {
        return this.comm;
    }
    
    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }




}


