package entities;
// Generated 24/04/2019 05:26:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private String projno;
     private String projname;
     private String deptno;
     private String respemp;
     private BigDecimal prstaff;
     private Date prstdate;
     private Date prendate;
     private String majproj;

    public Project() {
    }

	
    public Project(String projno, String projname, String deptno, String respemp) {
        this.projno = projno;
        this.projname = projname;
        this.deptno = deptno;
        this.respemp = respemp;
    }
    public Project(String projno, String projname, String deptno, String respemp, BigDecimal prstaff, Date prstdate, Date prendate, String majproj) {
       this.projno = projno;
       this.projname = projname;
       this.deptno = deptno;
       this.respemp = respemp;
       this.prstaff = prstaff;
       this.prstdate = prstdate;
       this.prendate = prendate;
       this.majproj = majproj;
    }
   
    public String getProjno() {
        return this.projno;
    }
    
    public void setProjno(String projno) {
        this.projno = projno;
    }
    public String getProjname() {
        return this.projname;
    }
    
    public void setProjname(String projname) {
        this.projname = projname;
    }
    public String getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }
    public String getRespemp() {
        return this.respemp;
    }
    
    public void setRespemp(String respemp) {
        this.respemp = respemp;
    }
    public BigDecimal getPrstaff() {
        return this.prstaff;
    }
    
    public void setPrstaff(BigDecimal prstaff) {
        this.prstaff = prstaff;
    }
    public Date getPrstdate() {
        return this.prstdate;
    }
    
    public void setPrstdate(Date prstdate) {
        this.prstdate = prstdate;
    }
    public Date getPrendate() {
        return this.prendate;
    }
    
    public void setPrendate(Date prendate) {
        this.prendate = prendate;
    }
    public String getMajproj() {
        return this.majproj;
    }
    
    public void setMajproj(String majproj) {
        this.majproj = majproj;
    }




}


