/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db2_20191;

import entities.Employee;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OFhec
 */
public class p004 extends javax.swing.JFrame {

    private static DefaultTableModel modelo;
    EmployeeModel em = new EmployeeModel();
    DepartmentModel dm = new DepartmentModel();
    Emp_ActModel am=new Emp_ActModel();
    ProjectModel pm=new ProjectModel();
    
    final String deptno = "DEPTNO";
    final String deptname = "DEPTNAME";
    final String mgrno = "MGRNO";
    final String admrdept = "ADMRDEPT";
    final String location = "LOCATION";

    final String empno = "EMPNO";
    final String firstnme = "FIRSTNME";
    final String midinit = "MIDINIT";
    final String lastname = "LASTNAME";
    final String phoneno = "PHONENO";
    final String workdept = "WORKDEPT";
    final String hiredate = "HIREDATE";
    final String job = "JOB";
    final String edlevel = "EDLEVEL";
    final String sex = "SEX";
    final String birthdate = "BIRTHDATE";
    final String salary = "SALARY";
    final String bonus = "BONUS";
    final String comm = "COMM";
    
    final String projno="PROJNO";
    final String projname="PROJNAME";
    final String actno="ACTNO";
    final String emptime="EMPTIME";
    final String emstdate="EMSTDATE";
    final String emendate="EMENDATE";
    /**
     * Creates new form p004
     */
    public p004() {
        initComponents();
        setLocationRelativeTo(null);
         cb1.addItem("query33");
        cb1.addItem("query34");
        cb1.addItem("query35");
        cb1.addItem("query36");
        cb1.addItem("query37");
        cb1.addItem("query38");
        cb1.addItem("query39");
        cb1.addItem("query40");
        cb1.addItem("query41");
        cb1.addItem("query42");
        cb1.addItem("query43");
        query33();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setText("Ejecutar Consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel1.setText("Página 004");

        t3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t3);

        jButton2.setText("Página Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (cb1.getSelectedIndex() + 1) {
            case 1:
                query33();
                break;
            case 2:
                query34();
                break;
            case 3:
                query35();
                break;
            case 4:
                query36();
                break;
            case 5:
                query37();
                break;
            case 6:
                query38();
                break;
            case 7:
                query39();
                break;
            case 8:
                query40();
                break;
            case 9:
                query41();
                break;
            case 10:
                query42();
                break;
            case 11:
        {
            try {
                query43();
            } catch (ParseException ex) {
                Logger.getLogger(p004.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       p002 pg2 = new p002();
    pg2.setLocationRelativeTo(null);
    this.setVisible(false);
    pg2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void query33(){
    List<Employee> l1 = em.query33();

        modelo = new DefaultTableModel();
        modelo.addColumn(lastname);
        modelo.addColumn(firstnme);
        modelo.addColumn(deptname);
        Object[] object = new Object[3];
        for (Employee d : l1) {
            object[0] = d.getLastname();
            object[1] = d.getFirstnme();
            object[2] = d.getWorkdept().getDeptname();
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query34(){
    List<Object[]> l1 = em.query34();

        modelo = new DefaultTableModel();
        modelo.addColumn(lastname);
        modelo.addColumn(firstnme);
        modelo.addColumn(deptname);
        modelo.addColumn(job);
        Object[] object = new Object[4];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            object[3]=d[3];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query35(){
    List<Object[]> l1 = em.query35();

        modelo = new DefaultTableModel();
        modelo.addColumn(deptname);
        modelo.addColumn(lastname);
        modelo.addColumn(firstnme);
        Object[] object = new Object[3];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query36(){
    List<Object[]> l1 = em.query36();

        modelo = new DefaultTableModel();
        modelo.addColumn(deptname);
        modelo.addColumn(lastname);
        modelo.addColumn(firstnme);
        Object[] object = new Object[3];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query37(){
    List<Object[]> l1 = am.query37();

        modelo = new DefaultTableModel();
        modelo.addColumn(projno);
        modelo.addColumn(projname);
        modelo.addColumn(actno);
        Object[] object = new Object[3];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query38(){
    List<Object[]> l1 = am.query38();

        modelo = new DefaultTableModel();
        modelo.addColumn(empno);
        modelo.addColumn(lastname);
        modelo.addColumn(projno);
        Object[] object = new Object[3];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query39(){
    List<Object[]> l1 = am.query39();

        modelo = new DefaultTableModel();
        modelo.addColumn(empno);
        modelo.addColumn(projno);
        modelo.addColumn(projname);
        modelo.addColumn(actno);
        modelo.addColumn(emstdate);
        Object[] object = new Object[5];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            object[3] = d[3];
            object[4] = d[4];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query40(){
    List<Object[]> l1 = am.query40();

        modelo = new DefaultTableModel();
        modelo.addColumn(workdept);
        modelo.addColumn(lastname);
        modelo.addColumn(projname);
        modelo.addColumn(actno);
        Object[] object = new Object[4];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            object[3] = d[3];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query41(){
    List<Object[]> l1 = am.query41();

        modelo = new DefaultTableModel();
        modelo.addColumn(workdept);
        modelo.addColumn(lastname);
        modelo.addColumn(projname);
        modelo.addColumn(actno);
        Object[] object = new Object[4];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            object[3] = d[3];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query42(){
    List<Object[]> l1 = am.query42();

        modelo = new DefaultTableModel();
        modelo.addColumn(actno);
        modelo.addColumn(mgrno);
        modelo.addColumn(emstdate);
        modelo.addColumn(projno);
        modelo.addColumn(lastname);
        Object[] object = new Object[5];
        for (Object[] d : l1) {
            object[0] = d[0];
            object[1] = d[1];
            object[2] = d[2];
            object[3] = d[3];
            object[4] = d[4];
            modelo.addRow(object);
        }
        t3.setModel(modelo);
    }
    public void query43() throws ParseException{
    List<Employee> l1 = am.query43();
    List<Employee> l2 = am.query43();
    SimpleDateFormat formateador = new SimpleDateFormat("yyyy-mm-dd"); 
    
        modelo = new DefaultTableModel();
        modelo.addColumn(deptno);
        modelo.addColumn("MANAGER");
        modelo.addColumn("EMPLOYEE");
        modelo.addColumn("M_HIREDATE");
        modelo.addColumn("E_HIREDATE");
        Object[] object = new Object[5];
        for (Employee m : l1) {
            for (Employee e : l2) {
                
                if(formateador.parse(m.getHiredate().toString()).after(formateador.parse(e.getHiredate().toString())) 
                        && e.getWorkdept().getDeptno().contains("A00") 
                        && m.getEmpno().equalsIgnoreCase(e.getWorkdept().getMgrno())
                        ){
                object[0] = e.getWorkdept().getDeptno();
            object[1] = m.getLastname();
            object[2] = e.getLastname();
            object[3] = m.getHiredate();
            object[4] = e.getHiredate();
            modelo.addRow(object);
                }
            }
        }
        t3.setModel(modelo);
        
        
    }
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p004.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p004.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p004.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p004.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p004().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t3;
    // End of variables declaration//GEN-END:variables
}
